name: Get Changes
description: Change Something on a Page
title: "Editing a Page"
labels: ["changes"]
body:
  - type: input
    id: vanity
    attributes:
      label: Vanity URL
      description: What is your vanity URL?
    validations:
      required: true
  - type: textarea
    id: changes
    attributes:
      label: Changes Needed
      description: Explain what you need changing
    validations:
      required: true